#!/usr/bin/python

import sys

import Fish.Admin.game_visualizer as game_visualizer

ERROR_MESSAGE = "Usage: ./xgui <number of players (2 - 4 inclusive)>"

def usage_exit():
    print(ERROR_MESSAGE)
    sys.exit()
    
def main():

    if len(sys.argv) != 2:
        usage_exit()

    try:
        game_visualizer.run_visualizer(sys.argv[1])
    except ValueError:
        usage_exit()

if __name__ == "__main__":
    main()
